Check/task2
Lyosha0i/gitXT pull request #2
Opened 2022-01-12 13:23 UTC by Lyosha0i

2022-02-06 13:15 UTC, ViCDroboviC requested changes

2022-02-06 13:15 UTC, ViCDroboviC commented on Task 2/Task2.1/StringDemo.cs
> +        public char[] C{
Переименуй на что-то более информативное.

2022-02-06 13:15 UTC, ViCDroboviC commented on Task 2/Task2.1/StringDemo.cs
> +            for (int i = 0; i < a.c.Length; i++)if (a.c[i] != b.c[i]) return false;
```suggestion
            if (a == null || b == null || a.c.Length != b.c.Length)
            {
                return false;
            }
            for (int i = 0; i < a.c.Length; i++)
            {
                if (a.c[i] != b.c[i])
                {   
                    return false;
                }
            }
```

2022-02-06 13:15 UTC, ViCDroboviC commented on Task 2/Task2.1/StringDemo.cs
> +            foreach (var i in arr)n+=i.c.Length;
```suggestion
            foreach (var i in arr)
            {
                n += i.c.Length;
            }
```

2022-02-06 13:15 UTC, ViCDroboviC commented on Task 2/Task2.1/StringDemo.cs
> +                if (s.c[i] == cc) return i + 1;
```suggestion
                if (s.c[i] == cc) 
                {
                    return i + 1;
                }
```

2022-02-06 13:15 UTC, ViCDroboviC commented on Task 2/Task2.1/StringDemo.cs
> +                if (s.c[i] == cc) return i + 1;
```suggestion
            {
                if (s.c[i] == cc) 
                {
                    return i + 1;
                }
```

2022-02-06 13:15 UTC, ViCDroboviC commented on Task 2/Task2.1/StringDemo.cs
> +        }
```suggestion
        public static char[] StrDToCharArr(StringDemo s)
        {
            return s.c;
        }
```

2022-02-06 13:15 UTC, ViCDroboviC commented on Task 2/Task2.1/StringDemo.cs
> +        }
Разверни в несколько строк.

2022-02-06 13:15 UTC, ViCDroboviC commented on Task 2/Task2.1/StringDemo.cs
> +            for (int i = 0; i < s.c.Length; i++) if (s.c[i] == cc) a++;
Аналогично

2022-02-06 13:15 UTC, ViCDroboviC commented on Task 2/Task2.1.2/Line.cs
> +    class Line:Figure
В данном случае все - же не корректное наследование, т.к. фигура явно описывает что-то, у чего есть площадь.

2022-02-06 13:15 UTC, ViCDroboviC commented on Task 2/Task2.1.2/Line.cs
> +        private int x1, x2, y1, y2;
```suggestion
        private Point startPoint;
        private Point endPoint;

```
Тут неплохо было бы ввести отдельный класс для точки, т.к. им можно будет и центр с вершинами для фигур описывать.

2022-02-06 16:48 UTC, Lyosha0i commented on Task 2/Task2.1/StringDemo.cs
> +        public char[] C{
Сделано.

2022-02-07 11:45 UTC, Lyosha0i commented on Task 2/Task2.1.2/Line.cs
> +        private int x1, x2, y1, y2;
Тогда было бы неплохо и остальные классы переделать.

2022-02-07 11:46 UTC, Lyosha0i commented on Task 2/Task2.1.2/Line.cs
> +    class Line:Figure
Так-то я понимаю, что как правило у линий площадь не вычисляют.
Стоит ли создавать ещё один класс между линиями и фигурами?

2022-02-13 08:57 UTC, ViCDroboviC approved these changes

2022-03-07 17:34 UTC, merged