Check/task3
Lyosha0i/gitXT pull request #3
Opened 2022-02-03 09:20 UTC by Lyosha0i

2022-02-13 09:51 UTC, ViCDroboviC requested changes

2022-02-13 09:51 UTC, ViCDroboviC commented on Task 3/Task3.1.2/Program.cs
> +            Console.ReadKey(true);
На будущее лучше выделять подобное в какой нибудь класс обработчик и в отдельном методе принимать скажем строку и максимальное число повторений, после которого будет считаться, что автор часто повторяется.

2022-02-13 09:51 UTC, ViCDroboviC commented on Task 3/Task3.1/Program.cs
> +                        node.Value = false;//Cross selected person out, and he won't exist.
За использование связанного списка +. Но попробуй отвязатся от использования <bool> в пользу условного <T> и чтобы элемент именно удалялся из коллекции. Ссылка для размышления:
https://ru.stackoverflow.com/questions/897467/%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2-%D0%BF%D0%BE-%D0%BA%D1%80%D1%83%D0%B3%D1%83

2022-02-13 09:51 UTC, ViCDroboviC commented on Task 3/Task3.2/DynamicArray.cs
> +        public T this[int index]
Индексаторы помещаются после конструкторов и свойств.

2022-02-13 09:51 UTC, ViCDroboviC commented on Task 3/Task3.2/DynamicArray.cs
> +        }
```suggestion
        public int Length
        {
            get
            {
                return data.Length;
            }
        }
        public int Capacity
        {
            get
            {
                return capacity;
            }
            set
            {
                if (capacity >= Length)
                    capacity = value;
            }
        }
```
1) Не совсем понял зачем тебе тут три свойства для описания размеров коллекции.
2) Не корректно давать пользователю давать возможность менять Length т.к. это свойство все таки характеризует кол-во элементов в коллекции и вилять он должен на это свойство именно добавление/удалением элементов.
3) Нельзя давать возможность задать емкость коллекции меньше, чем кол-во элементов в нем, чтобы избежать потери данных.

2022-02-13 09:51 UTC, ViCDroboviC commented on Task 3/Task3.2/DynamicArray.cs
> +        public void AddInsert()
Поправь этот метод с учетом замечаний по поводу свойств.

2022-02-13 09:51 UTC, ViCDroboviC commented on Task 3/Task3.3.2/SuperString.cs
> +    static class SuperString
```suggestion
    static class StringExtensions
```

2022-02-13 09:51 UTC, ViCDroboviC commented on Task 3/Task3.3.3/Program.cs
> +        }
Выдели всю логику пицерии в отдельный класс (нестатический). Выдели у него скажем два события - у одного делегат будет возвращать числовой номер заказа, а второе будет сигнализировать о готовности заказа.

2022-02-13 10:10 UTC, ViCDroboviC requested changes

2022-02-13 10:10 UTC, ViCDroboviC commented on Task 3/Task3.2/DynamicArray.cs
> +        }
```suggestion
        private T[] data;
        
        public DynamicArray()
        {
            Array.Resize(ref data, Capacity);
        }
```
Не забывай разделять члены класса пустой строкой. И еще не увидел конструктор с целочисленным параметром.

2022-02-13 11:14 UTC, Lyosha0i commented on Task 3/Task3.2/DynamicArray.cs
> +        public T this[int index]
Я думал, индексаторы и свойства можно перемешать. Учту на будущее.👌

2022-02-13 11:28 UTC, Lyosha0i commented on Task 3/Task3.2/DynamicArray.cs
> +        }
1. Да я просто хотел, чтобы как у всех нормальных коллекций было свойство Count.🤔
2. Согласен. Поторопился.
3. Я просто неправильно сначала понял дополнительный пункт про ручное изменение ёмкости.

2022-02-13 11:31 UTC, Lyosha0i commented on Task 3/Task3.3.2/SuperString.cs
> +    static class SuperString
Твой вариант мне больше нравится. Просто это задание так называется.

2022-02-13 11:33 UTC, Lyosha0i commented on Task 3/Task3.3.3/Program.cs
> +        }
Гм, а почему так лучше? Будет ли программа лучше работать?

2022-02-13 16:38 UTC, Lyosha0i commented on Task 3/Task3.2/DynamicArray.cs
> +        }
Сделал этот конструктор.

2022-02-13 17:53 UTC, Lyosha0i commented on Task 3/Task3.2/DynamicArray.cs
> +        }
2. Может быть, я тогда недостаточно хорошо подумал, но теперь AddRange сломался.

2022-02-14 06:12 UTC, Lyosha0i commented on Task 3/Task3.2/DynamicArray.cs
> +        }
2. Я очень извиняюсь. Я из-за спешки умудрился сломать геттер, а там и AddRange. Теперь всё работает.👌

2022-03-07 09:18 UTC, ViCDroboviC commented on Task 3/Task3.3.3/Program.cs
> +        }
Так будет правильнее с точки зрения единственной ответственности. Пиццерия не должна создавать новый заказ, ее ответственность это принять заказ, исполнить его, а затем каким либо образом оповестить клиента о готовности заказа (например через класс InfoTable который будет выводить на консоль).

2022-03-07 17:27 UTC, Lyosha0i commented on Task 3/Task3.3.3/Program.cs
> +        }
Кажется, я так и сделал, добавив события.

2022-03-20 16:23 UTC, ViCDroboviC commented on Task 3/Task3.3.3/Program.cs
> +        }
У тебя в классе пиццерии есть сами события, но на них никто не подписывается. На 32 строке была какая-то идея в правильную сторону, н видимо что-то не так пошло.)

2022-03-27 08:13 UTC, ViCDroboviC approved these changes

2022-09-10 17:30 UTC, merged