check/task4
Lyosha0i/gitXT pull request #4
Opened 2022-02-27 11:21 UTC by Lyosha0i

2022-04-10 07:05 UTC, ViCDroboviC requested changes

2022-04-10 07:05 UTC, ViCDroboviC commented on Task 4/Task4.1/Bridge.cs
> +        public static Bridge Instance
Для чего тебе это свойство?

2022-04-10 07:05 UTC, ViCDroboviC commented on Task 4/Task4.1/Program.cs
> +        }
Выдели под логику "наблюдателя" отдельный класс. Аналогично нужно будет поступить и с обработчиками событий. А в мейне оставить скажем инициализацию наблюдателя и обработчика, а так - же подпись на события наблюдателя.

2022-04-10 07:05 UTC, ViCDroboviC commented on Task 4/Task4.1/Bridge.cs
> +        public static Bridge Instance
Почему бы не инициализировать новый экземпляр Bridge в вызывающем коде, а то обращение к свойствам класса через свойство, которое проверяет наличие экземпляра это что то очень инородное. Вся боль по проверке на null лежит на вызывающем коде, и внутри этого класса тебя это не должно волновать.

2022-05-06 16:58 UTC, Lyosha0i commented on Task 4/Task4.1/Bridge.cs
> +        public static Bridge Instance
Я решил сделать синглтон. Вот и получается, что я таким образом проверяю наличие экземпляра. Неужели здесь синглтон не к месту?🤔
А свойство это я сделал, предполагая, что надо бы сделать защиту от дурака.

2022-05-08 17:38 UTC, Lyosha0i commented on Task 4/Task4.1/Program.cs
> +        }
Я попробовал. Не получилось.

2022-09-10 17:30 UTC, merged